import os

def w(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True) if os.path.dirname(path) else None
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"OK: {path}")

# src/api/axios.js
w("src/api/axios.js", [
    'import axios from "axios"',
    '',
    'const api = axios.create({',
    '  baseURL: import.meta.env.VITE_API_URL || "http://127.0.0.1:8000",',
    '})',
    '',
    'api.interceptors.request.use((config) => {',
    '  const token = localStorage.getItem("token")',
    '  if (token) config.headers.Authorization = `Bearer ${token}`',
    '  return config',
    '})',
    '',
    'api.interceptors.response.use(',
    '  (response) => response,',
    '  (error) => {',
    '    if (error.response?.status === 401) {',
    '      localStorage.removeItem("token")',
    '      localStorage.removeItem("user")',
    '      window.location.href = "/login"',
    '    }',
    '    return Promise.reject(error)',
    '  }',
    ')',
    '',
    'export default api',
])

# src/context/AuthContext.jsx
w("src/context/AuthContext.jsx", [
    'import { createContext, useContext, useState } from "react"',
    '',
    'const AuthContext = createContext(null)',
    '',
    'export function AuthProvider({ children }) {',
    '  const [user, setUser] = useState(() => {',
    '    const saved = localStorage.getItem("user")',
    '    return saved ? JSON.parse(saved) : null',
    '  })',
    '',
    '  const login = (userData, token) => {',
    '    localStorage.setItem("token", token)',
    '    localStorage.setItem("user", JSON.stringify(userData))',
    '    setUser(userData)',
    '  }',
    '',
    '  const logout = () => {',
    '    localStorage.removeItem("token")',
    '    localStorage.removeItem("user")',
    '    setUser(null)',
    '  }',
    '',
    '  return (',
    '    <AuthContext.Provider value={{ user, login, logout }}>',
    '      {children}',
    '    </AuthContext.Provider>',
    '  )',
    '}',
    '',
    'export function useAuth() {',
    '  return useContext(AuthContext)',
    '}',
])

# src/components/PrivateRoute.jsx
w("src/components/PrivateRoute.jsx", [
    'import { Navigate } from "react-router-dom"',
    'import { useAuth } from "../context/AuthContext"',
    '',
    'export default function PrivateRoute({ children, adminOnly = false }) {',
    '  const { user } = useAuth()',
    '  if (!user) return <Navigate to="/login" />',
    '  if (adminOnly && user.role !== "admin") return <Navigate to="/" />',
    '  return children',
    '}',
])

# src/components/Navbar.jsx
w("src/components/Navbar.jsx", [
    'import { Link, useNavigate } from "react-router-dom"',
    'import { useAuth } from "../context/AuthContext"',
    '',
    'export default function Navbar() {',
    '  const { user, logout } = useAuth()',
    '  const navigate = useNavigate()',
    '',
    '  const handleLogout = () => {',
    '    logout()',
    '    navigate("/login")',
    '  }',
    '',
    '  return (',
    '    <nav style={styles.nav}>',
    '      <div style={styles.brand}>CSC Licitaciones</div>',
    '      <div style={styles.links}>',
    '        <Link to="/" style={styles.link}>Licitaciones</Link>',
    '        <Link to="/clients" style={styles.link}>Clientes</Link>',
    '        <Link to="/products" style={styles.link}>Productos</Link>',
    '        {user?.role === "admin" && <Link to="/users" style={styles.link}>Usuarios</Link>}',
    '        <span style={styles.userInfo}>{user?.name}</span>',
    '        <button onClick={handleLogout} style={styles.btn}>Salir</button>',
    '      </div>',
    '    </nav>',
    '  )',
    '}',
    '',
    'const styles = {',
    '  nav: { display:"flex", justifyContent:"space-between", alignItems:"center", padding:"12px 24px", background:"#1e3a5f", color:"white" },',
    '  brand: { fontWeight:"bold", fontSize:"18px", color:"white" },',
    '  links: { display:"flex", gap:"16px", alignItems:"center" },',
    '  link: { color:"white", textDecoration:"none", fontSize:"14px" },',
    '  userInfo: { color:"#a0c4ff", fontSize:"14px" },',
    '  btn: { background:"#e74c3c", color:"white", border:"none", padding:"6px 12px", borderRadius:"4px", cursor:"pointer" }',
    '}',
])

# src/pages/Login.jsx
w("src/pages/Login.jsx", [
    'import { useState } from "react"',
    'import { useNavigate } from "react-router-dom"',
    'import { useAuth } from "../context/AuthContext"',
    'import api from "../api/axios"',
    '',
    'export default function Login() {',
    '  const [email, setEmail] = useState("")',
    '  const [password, setPassword] = useState("")',
    '  const [error, setError] = useState("")',
    '  const [loading, setLoading] = useState(false)',
    '  const { login } = useAuth()',
    '  const navigate = useNavigate()',
    '',
    '  const handleSubmit = async (e) => {',
    '    e.preventDefault()',
    '    setError("")',
    '    setLoading(true)',
    '    try {',
    '      const res = await api.post("/api/auth/login", { email, password })',
    '      login(res.data.user, res.data.access_token)',
    '      navigate("/")',
    '    } catch (err) {',
    '      setError(err.response?.data?.detail || "Credenciales incorrectas")',
    '    } finally {',
    '      setLoading(false)',
    '    }',
    '  }',
    '',
    '  return (',
    '    <div style={styles.container}>',
    '      <div style={styles.card}>',
    '        <h1 style={styles.title}>CSC Licitaciones</h1>',
    '        <h2 style={styles.subtitle}>Iniciar Sesión</h2>',
    '        {error && <div style={styles.error}>{error}</div>}',
    '        <form onSubmit={handleSubmit}>',
    '          <div style={styles.field}>',
    '            <label style={styles.label}>Email</label>',
    '            <input style={styles.input} type="email" value={email} onChange={e => setEmail(e.target.value)} required />',
    '          </div>',
    '          <div style={styles.field}>',
    '            <label style={styles.label}>Contraseña</label>',
    '            <input style={styles.input} type="password" value={password} onChange={e => setPassword(e.target.value)} required />',
    '          </div>',
    '          <button style={styles.btn} type="submit" disabled={loading}>',
    '            {loading ? "Ingresando..." : "Ingresar"}',
    '          </button>',
    '        </form>',
    '      </div>',
    '    </div>',
    '  )',
    '}',
    '',
    'const styles = {',
    '  container: { minHeight:"100vh", display:"flex", alignItems:"center", justifyContent:"center", background:"#f0f4f8" },',
    '  card: { background:"white", padding:"40px", borderRadius:"8px", boxShadow:"0 2px 10px rgba(0,0,0,0.1)", width:"360px" },',
    '  title: { textAlign:"center", color:"#1e3a5f", margin:"0 0 4px" },',
    '  subtitle: { textAlign:"center", color:"#666", margin:"0 0 24px", fontWeight:"normal", fontSize:"16px" },',
    '  error: { background:"#fee", color:"#c00", padding:"10px", borderRadius:"4px", marginBottom:"16px", fontSize:"14px" },',
    '  field: { marginBottom:"16px" },',
    '  label: { display:"block", marginBottom:"6px", fontSize:"14px", color:"#333" },',
    '  input: { width:"100%", padding:"10px", border:"1px solid #ddd", borderRadius:"4px", fontSize:"14px", boxSizing:"border-box" },',
    '  btn: { width:"100%", padding:"12px", background:"#1e3a5f", color:"white", border:"none", borderRadius:"4px", fontSize:"16px", cursor:"pointer" }',
    '}',
])

# src/pages/Tenders.jsx
w("src/pages/Tenders.jsx", [
    'import { useState, useEffect } from "react"',
    'import { useNavigate } from "react-router-dom"',
    'import api from "../api/axios"',
    '',
    'export default function Tenders() {',
    '  const [tenders, setTenders] = useState([])',
    '  const [clients, setClients] = useState([])',
    '  const [showForm, setShowForm] = useState(false)',
    '  const [form, setForm] = useState({ title:"", description:"", client_id:"", max_budget:"" })',
    '  const [error, setError] = useState("")',
    '  const navigate = useNavigate()',
    '',
    '  useEffect(() => {',
    '    api.get("/api/tenders").then(r => setTenders(r.data))',
    '    api.get("/api/clients").then(r => setClients(r.data))',
    '  }, [])',
    '',
    '  const handleCreate = async (e) => {',
    '    e.preventDefault()',
    '    setError("")',
    '    try {',
    '      const res = await api.post("/api/tenders", { ...form, client_id: parseInt(form.client_id), max_budget: parseFloat(form.max_budget) })',
    '      setTenders([...tenders, res.data])',
    '      setShowForm(false)',
    '      setForm({ title:"", description:"", client_id:"", max_budget:"" })',
    '    } catch (err) {',
    '      setError(err.response?.data?.detail || "Error al crear licitación")',
    '    }',
    '  }',
    '',
    '  const statusColors = { activa:"#27ae60", por_cobrar:"#f39c12", perdida:"#e74c3c", finalizada:"#7f8c8d" }',
    '',
    '  return (',
    '    <div style={styles.container}>',
    '      <div style={styles.header}>',
    '        <h2>Licitaciones</h2>',
    '        <button style={styles.btnPrimary} onClick={() => setShowForm(!showForm)}>+ Nueva Licitación</button>',
    '      </div>',
    '',
    '      {showForm && (',
    '        <div style={styles.formCard}>',
    '          <h3>Crear Licitación</h3>',
    '          {error && <div style={styles.error}>{error}</div>}',
    '          <form onSubmit={handleCreate}>',
    '            <input style={styles.input} placeholder="Título" value={form.title} onChange={e => setForm({...form, title:e.target.value})} required />',
    '            <textarea style={styles.input} placeholder="Descripción" value={form.description} onChange={e => setForm({...form, description:e.target.value})} />',
    '            <select style={styles.input} value={form.client_id} onChange={e => setForm({...form, client_id:e.target.value})} required>',
    '              <option value="">Seleccionar cliente</option>',
    '              {clients.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}',
    '            </select>',
    '            <input style={styles.input} type="number" placeholder="Presupuesto máximo" value={form.max_budget} onChange={e => setForm({...form, max_budget:e.target.value})} required />',
    '            <div style={{display:"flex", gap:"8px"}}>',
    '              <button style={styles.btnPrimary} type="submit">Crear</button>',
    '              <button style={styles.btnSecondary} type="button" onClick={() => setShowForm(false)}>Cancelar</button>',
    '            </div>',
    '          </form>',
    '        </div>',
    '      )}',
    '',
    '      <table style={styles.table}>',
    '        <thead><tr>',
    '          <th style={styles.th}>Título</th>',
    '          <th style={styles.th}>Cliente</th>',
    '          <th style={styles.th}>Estado</th>',
    '          <th style={styles.th}>Presupuesto</th>',
    '          <th style={styles.th}>Total</th>',
    '          <th style={styles.th}>Acciones</th>',
    '        </tr></thead>',
    '        <tbody>',
    '          {tenders.map(t => (',
    '            <tr key={t.id}>',
    '              <td style={styles.td}>{t.title}</td>',
    '              <td style={styles.td}>{t.client?.name || "-"}</td>',
    '              <td style={styles.td}><span style={{...styles.badge, background:statusColors[t.status]}}>{t.status}</span></td>',
    '              <td style={styles.td}>${parseFloat(t.max_budget).toFixed(2)}</td>',
    '              <td style={styles.td}>${parseFloat(t.total_amount).toFixed(2)}</td>',
    '              <td style={styles.td}><button style={styles.btnSmall} onClick={() => navigate(`/tenders/${t.id}`)}>Ver</button></td>',
    '            </tr>',
    '          ))}',
    '        </tbody>',
    '      </table>',
    '    </div>',
    '  )',
    '}',
    '',
    'const styles = {',
    '  container: { padding:"24px" },',
    '  header: { display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:"20px" },',
    '  formCard: { background:"white", padding:"20px", borderRadius:"8px", boxShadow:"0 2px 8px rgba(0,0,0,0.1)", marginBottom:"20px" },',
    '  error: { background:"#fee", color:"#c00", padding:"10px", borderRadius:"4px", marginBottom:"12px", fontSize:"14px" },',
    '  input: { display:"block", width:"100%", padding:"10px", margin:"8px 0", border:"1px solid #ddd", borderRadius:"4px", fontSize:"14px", boxSizing:"border-box" },',
    '  table: { width:"100%", borderCollapse:"collapse", background:"white", borderRadius:"8px", overflow:"hidden", boxShadow:"0 2px 8px rgba(0,0,0,0.1)" },',
    '  th: { padding:"12px 16px", background:"#1e3a5f", color:"white", textAlign:"left", fontSize:"14px" },',
    '  td: { padding:"12px 16px", borderBottom:"1px solid #eee", fontSize:"14px" },',
    '  badge: { padding:"4px 10px", borderRadius:"12px", color:"white", fontSize:"12px", fontWeight:"bold" },',
    '  btnPrimary: { background:"#1e3a5f", color:"white", border:"none", padding:"10px 20px", borderRadius:"4px", cursor:"pointer", fontSize:"14px" },',
    '  btnSecondary: { background:"#95a5a6", color:"white", border:"none", padding:"10px 20px", borderRadius:"4px", cursor:"pointer", fontSize:"14px" },',
    '  btnSmall: { background:"#3498db", color:"white", border:"none", padding:"6px 12px", borderRadius:"4px", cursor:"pointer", fontSize:"12px" }',
    '}',
])

# src/pages/TenderDetail.jsx
w("src/pages/TenderDetail.jsx", [
    'import { useState, useEffect } from "react"',
    'import { useParams } from "react-router-dom"',
    'import api from "../api/axios"',
    '',
    'const VALID_TRANSITIONS = {',
    '  activa: ["por_cobrar", "perdida"],',
    '  por_cobrar: ["finalizada"],',
    '  finalizada: [],',
    '  perdida: []',
    '}',
    '',
    'export default function TenderDetail() {',
    '  const { id } = useParams()',
    '  const [tender, setTender] = useState(null)',
    '  const [products, setProducts] = useState([])',
    '  const [showAddProduct, setShowAddProduct] = useState(false)',
    '  const [form, setForm] = useState({ product_id: "", quantity: 1 })',
    '  const [error, setError] = useState("")',
    '  const [success, setSuccess] = useState("")',
    '',
    '  useEffect(() => {',
    '    loadTender()',
    '    api.get("/api/products").then(r => setProducts(r.data))',
    '  }, [id])',
    '',
    '  const loadTender = async () => {',
    '    const res = await api.get(`/api/tenders/${id}`)',
    '    setTender(res.data)',
    '  }',
    '',
    '  const handleAddProduct = async (e) => {',
    '    e.preventDefault()',
    '    setError("")',
    '    try {',
    '      await api.post(`/api/tenders/${id}/products`, { product_id: parseInt(form.product_id), quantity: parseInt(form.quantity) })',
    '      setSuccess("Producto agregado exitosamente")',
    '      setShowAddProduct(false)',
    '      setForm({ product_id: "", quantity: 1 })',
    '      loadTender()',
    '      setTimeout(() => setSuccess(""), 3000)',
    '    } catch (err) {',
    '      setError(err.response?.data?.detail || "Error al agregar producto")',
    '    }',
    '  }',
    '',
    '  const handleStatusChange = async (newStatus) => {',
    '    setError("")',
    '    try {',
    '      await api.patch(`/api/tenders/${id}/status`, { status: newStatus })',
    '      loadTender()',
    '    } catch (err) {',
    '      setError(err.response?.data?.detail || "Error al cambiar estado")',
    '    }',
    '  }',
    '',
    '  if (!tender) return <div style={{padding:"24px"}}>Cargando...</div>',
    '',
    '  const budget = parseFloat(tender.max_budget)',
    '  const total = parseFloat(tender.total_amount)',
    '  const percentage = budget > 0 ? Math.min((total / budget) * 100, 100) : 0',
    '  const barColor = percentage > 90 ? "#e74c3c" : percentage > 70 ? "#f39c12" : "#27ae60"',
    '  const statusColors = { activa:"#27ae60", por_cobrar:"#f39c12", perdida:"#e74c3c", finalizada:"#7f8c8d" }',
    '  const nextStatuses = VALID_TRANSITIONS[tender.status] || []',
    '',
    '  return (',
    '    <div style={styles.container}>',
    '      <div style={styles.card}>',
    '        <div style={styles.cardHeader}>',
    '          <h2>{tender.title}</h2>',
    '          <span style={{...styles.badge, background:statusColors[tender.status]}}>{tender.status}</span>',
    '        </div>',
    '        <p style={{color:"#666"}}>{tender.description}</p>',
    '        <p><strong>Cliente:</strong> {tender.client?.name}</p>',
    '',
    '        <div style={styles.budgetSection}>',
    '          <div style={styles.budgetRow}>',
    '            <span>Presupuesto: ${budget.toFixed(2)}</span>',
    '            <span>Total: ${total.toFixed(2)}</span>',
    '            <span>{percentage.toFixed(1)}% utilizado</span>',
    '          </div>',
    '          <div style={styles.progressBar}>',
    '            <div style={{...styles.progressFill, width:`${percentage}%`, background:barColor}} />',
    '          </div>',
    '        </div>',
    '',
    '        {error && <div style={styles.error}>{error}</div>}',
    '        {success && <div style={styles.success}>{success}</div>}',
    '',
    '        {nextStatuses.length > 0 && (',
    '          <div style={styles.statusSection}>',
    '            <strong>Cambiar estado:</strong>',
    '            {nextStatuses.map(s => (',
    '              <button key={s} style={{...styles.btnStatus, background:statusColors[s]}} onClick={() => handleStatusChange(s)}>',
    '                → {s}',
    '              </button>',
    '            ))}',
    '          </div>',
    '        )}',
    '      </div>',
    '',
    '      <div style={styles.card}>',
    '        <div style={styles.cardHeader}>',
    '          <h3>Productos</h3>',
    '          {tender.status === "activa" && (',
    '            <button style={styles.btnPrimary} onClick={() => setShowAddProduct(!showAddProduct)}>+ Agregar Producto</button>',
    '          )}',
    '        </div>',
    '',
    '        {showAddProduct && (',
    '          <form onSubmit={handleAddProduct} style={{marginBottom:"16px"}}> ',
    '            <select style={styles.input} value={form.product_id} onChange={e => setForm({...form, product_id:e.target.value})} required>',
    '              <option value="">Seleccionar producto</option>',
    '              {products.map(p => <option key={p.id} value={p.id}>{p.name} - ${parseFloat(p.unit_price).toFixed(2)}</option>)}',
    '            </select>',
    '            <input style={styles.input} type="number" min="1" placeholder="Cantidad" value={form.quantity} onChange={e => setForm({...form, quantity:e.target.value})} required />',
    '            <div style={{display:"flex", gap:"8px"}}>',
    '              <button style={styles.btnPrimary} type="submit">Agregar</button>',
    '              <button style={styles.btnSecondary} type="button" onClick={() => setShowAddProduct(false)}>Cancelar</button>',
    '            </div>',
    '          </form>',
    '        )}',
    '',
    '        <table style={styles.table}>',
    '          <thead><tr>',
    '            <th style={styles.th}>Producto</th>',
    '            <th style={styles.th}>SKU</th>',
    '            <th style={styles.th}>Cantidad</th>',
    '            <th style={styles.th}>Precio Unit.</th>',
    '            <th style={styles.th}>Subtotal</th>',
    '          </tr></thead>',
    '          <tbody>',
    '            {tender.products?.map(p => (',
    '              <tr key={p.id}>',
    '                <td style={styles.td}>{p.product?.name}</td>',
    '                <td style={styles.td}>{p.product?.sku}</td>',
    '                <td style={styles.td}>{p.quantity}</td>',
    '                <td style={styles.td}>${parseFloat(p.unit_price).toFixed(2)}</td>',
    '                <td style={styles.td}>${(parseFloat(p.unit_price) * p.quantity).toFixed(2)}</td>',
    '              </tr>',
    '            ))}',
    '          </tbody>',
    '        </table>',
    '      </div>',
    '    </div>',
    '  )',
    '}',
    '',
    'const styles = {',
    '  container: { padding:"24px", maxWidth:"900px", margin:"0 auto" },',
    '  card: { background:"white", padding:"24px", borderRadius:"8px", boxShadow:"0 2px 8px rgba(0,0,0,0.1)", marginBottom:"20px" },',
    '  cardHeader: { display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:"12px" },',
    '  badge: { padding:"6px 14px", borderRadius:"12px", color:"white", fontSize:"13px", fontWeight:"bold" },',
    '  budgetSection: { marginTop:"16px" },',
    '  budgetRow: { display:"flex", gap:"24px", marginBottom:"8px", fontSize:"14px" },',
    '  progressBar: { height:"12px", background:"#eee", borderRadius:"6px", overflow:"hidden" },',
    '  progressFill: { height:"100%", borderRadius:"6px", transition:"width 0.3s" },',
    '  statusSection: { display:"flex", gap:"8px", alignItems:"center", marginTop:"16px", flexWrap:"wrap" },',
    '  error: { background:"#fee", color:"#c00", padding:"10px", borderRadius:"4px", margin:"12px 0", fontSize:"14px" },',
    '  success: { background:"#efe", color:"#060", padding:"10px", borderRadius:"4px", margin:"12px 0", fontSize:"14px" },',
    '  input: { display:"block", width:"100%", padding:"10px", margin:"8px 0", border:"1px solid #ddd", borderRadius:"4px", fontSize:"14px", boxSizing:"border-box" },',
    '  table: { width:"100%", borderCollapse:"collapse" },',
    '  th: { padding:"10px 12px", background:"#f5f5f5", textAlign:"left", fontSize:"13px", borderBottom:"2px solid #ddd" },',
    '  td: { padding:"10px 12px", borderBottom:"1px solid #eee", fontSize:"14px" },',
    '  btnPrimary: { background:"#1e3a5f", color:"white", border:"none", padding:"10px 20px", borderRadius:"4px", cursor:"pointer", fontSize:"14px" },',
    '  btnSecondary: { background:"#95a5a6", color:"white", border:"none", padding:"10px 20px", borderRadius:"4px", cursor:"pointer", fontSize:"14px" },',
    '  btnStatus: { color:"white", border:"none", padding:"8px 16px", borderRadius:"4px", cursor:"pointer", fontSize:"13px" }',
    '}',
])

# src/pages/Clients.jsx
w("src/pages/Clients.jsx", [
    'import { useState, useEffect } from "react"',
    'import api from "../api/axios"',
    'import { useAuth } from "../context/AuthContext"',
    '',
    'export default function Clients() {',
    '  const [clients, setClients] = useState([])',
    '  const [showForm, setShowForm] = useState(false)',
    '  const [form, setForm] = useState({ name:"", email:"", phone:"" })',
    '  const [error, setError] = useState("")',
    '  const { user } = useAuth()',
    '',
    '  useEffect(() => {',
    '    api.get("/api/clients").then(r => setClients(r.data))',
    '  }, [])',
    '',
    '  const handleCreate = async (e) => {',
    '    e.preventDefault()',
    '    setError("")',
    '    try {',
    '      const res = await api.post("/api/clients", form)',
    '      setClients([...clients, res.data])',
    '      setShowForm(false)',
    '      setForm({ name:"", email:"", phone:"" })',
    '    } catch (err) {',
    '      setError(err.response?.data?.detail || "Error al crear cliente")',
    '    }',
    '  }',
    '',
    '  return (',
    '    <div style={styles.container}>',
    '      <div style={styles.header}>',
    '        <h2>Clientes</h2>',
    '        {user?.role === "admin" && <button style={styles.btnPrimary} onClick={() => setShowForm(!showForm)}>+ Nuevo Cliente</button>}',
    '      </div>',
    '',
    '      {showForm && (',
    '        <div style={styles.formCard}>',
    '          <h3>Crear Cliente</h3>',
    '          {error && <div style={styles.error}>{error}</div>}',
    '          <form onSubmit={handleCreate}>',
    '            <input style={styles.input} placeholder="Nombre *" value={form.name} onChange={e => setForm({...form, name:e.target.value})} required />',
    '            <input style={styles.input} placeholder="Email" value={form.email} onChange={e => setForm({...form, email:e.target.value})} />',
    '            <input style={styles.input} placeholder="Teléfono" value={form.phone} onChange={e => setForm({...form, phone:e.target.value})} />',
    '            <div style={{display:"flex", gap:"8px"}}>',
    '              <button style={styles.btnPrimary} type="submit">Crear</button>',
    '              <button style={styles.btnSecondary} type="button" onClick={() => setShowForm(false)}>Cancelar</button>',
    '            </div>',
    '          </form>',
    '        </div>',
    '      )}',
    '',
    '      <table style={styles.table}>',
    '        <thead><tr>',
    '          <th style={styles.th}>Nombre</th>',
    '          <th style={styles.th}>Email</th>',
    '          <th style={styles.th}>Teléfono</th>',
    '        </tr></thead>',
    '        <tbody>',
    '          {clients.map(c => (',
    '            <tr key={c.id}>',
    '              <td style={styles.td}>{c.name}</td>',
    '              <td style={styles.td}>{c.email || "-"}</td>',
    '              <td style={styles.td}>{c.phone || "-"}</td>',
    '            </tr>',
    '          ))}',
    '        </tbody>',
    '      </table>',
    '    </div>',
    '  )',
    '}',
    '',
    'const styles = {',
    '  container: { padding:"24px" },',
    '  header: { display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:"20px" },',
    '  formCard: { background:"white", padding:"20px", borderRadius:"8px", boxShadow:"0 2px 8px rgba(0,0,0,0.1)", marginBottom:"20px" },',
    '  error: { background:"#fee", color:"#c00", padding:"10px", borderRadius:"4px", marginBottom:"12px", fontSize:"14px" },',
    '  input: { display:"block", width:"100%", padding:"10px", margin:"8px 0", border:"1px solid #ddd", borderRadius:"4px", fontSize:"14px", boxSizing:"border-box" },',
    '  table: { width:"100%", borderCollapse:"collapse", background:"white", borderRadius:"8px", overflow:"hidden", boxShadow:"0 2px 8px rgba(0,0,0,0.1)" },',
    '  th: { padding:"12px 16px", background:"#1e3a5f", color:"white", textAlign:"left", fontSize:"14px" },',
    '  td: { padding:"12px 16px", borderBottom:"1px solid #eee", fontSize:"14px" },',
    '  btnPrimary: { background:"#1e3a5f", color:"white", border:"none", padding:"10px 20px", borderRadius:"4px", cursor:"pointer", fontSize:"14px" },',
    '  btnSecondary: { background:"#95a5a6", color:"white", border:"none", padding:"10px 20px", borderRadius:"4px", cursor:"pointer", fontSize:"14px" }',
    '}',
])

# src/pages/Products.jsx
w("src/pages/Products.jsx", [
    'import { useState, useEffect } from "react"',
    'import api from "../api/axios"',
    'import { useAuth } from "../context/AuthContext"',
    '',
    'export default function Products() {',
    '  const [products, setProducts] = useState([])',
    '  const [showForm, setShowForm] = useState(false)',
    '  const [form, setForm] = useState({ name:"", sku:"", unit_price:"" })',
    '  const [error, setError] = useState("")',
    '  const { user } = useAuth()',
    '',
    '  useEffect(() => {',
    '    api.get("/api/products").then(r => setProducts(r.data))',
    '  }, [])',
    '',
    '  const handleCreate = async (e) => {',
    '    e.preventDefault()',
    '    setError("")',
    '    try {',
    '      const res = await api.post("/api/products", { ...form, unit_price: parseFloat(form.unit_price) })',
    '      setProducts([...products, res.data])',
    '      setShowForm(false)',
    '      setForm({ name:"", sku:"", unit_price:"" })',
    '    } catch (err) {',
    '      setError(err.response?.data?.detail || "Error al crear producto")',
    '    }',
    '  }',
    '',
    '  return (',
    '    <div style={styles.container}>',
    '      <div style={styles.header}>',
    '        <h2>Productos</h2>',
    '        {user?.role === "admin" && <button style={styles.btnPrimary} onClick={() => setShowForm(!showForm)}>+ Nuevo Producto</button>}',
    '      </div>',
    '',
    '      {showForm && (',
    '        <div style={styles.formCard}>',
    '          <h3>Crear Producto</h3>',
    '          {error && <div style={styles.error}>{error}</div>}',
    '          <form onSubmit={handleCreate}>',
    '            <input style={styles.input} placeholder="Nombre *" value={form.name} onChange={e => setForm({...form, name:e.target.value})} required />',
    '            <input style={styles.input} placeholder="SKU *" value={form.sku} onChange={e => setForm({...form, sku:e.target.value})} required />',
    '            <input style={styles.input} type="number" step="0.01" placeholder="Precio unitario *" value={form.unit_price} onChange={e => setForm({...form, unit_price:e.target.value})} required />',
    '            <div style={{display:"flex", gap:"8px"}}>',
    '              <button style={styles.btnPrimary} type="submit">Crear</button>',
    '              <button style={styles.btnSecondary} type="button" onClick={() => setShowForm(false)}>Cancelar</button>',
    '            </div>',
    '          </form>',
    '        </div>',
    '      )}',
    '',
    '      <table style={styles.table}>',
    '        <thead><tr>',
    '          <th style={styles.th}>Nombre</th>',
    '          <th style={styles.th}>SKU</th>',
    '          <th style={styles.th}>Precio Unitario</th>',
    '        </tr></thead>',
    '        <tbody>',
    '          {products.map(p => (',
    '            <tr key={p.id}>',
    '              <td style={styles.td}>{p.name}</td>',
    '              <td style={styles.td}>{p.sku}</td>',
    '              <td style={styles.td}>${parseFloat(p.unit_price).toFixed(2)}</td>',
    '            </tr>',
    '          ))}',
    '        </tbody>',
    '      </table>',
    '    </div>',
    '  )',
    '}',
    '',
    'const styles = {',
    '  container: { padding:"24px" },',
    '  header: { display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:"20px" },',
    '  formCard: { background:"white", padding:"20px", borderRadius:"8px", boxShadow:"0 2px 8px rgba(0,0,0,0.1)", marginBottom:"20px" },',
    '  error: { background:"#fee", color:"#c00", padding:"10px", borderRadius:"4px", marginBottom:"12px", fontSize:"14px" },',
    '  input: { display:"block", width:"100%", padding:"10px", margin:"8px 0", border:"1px solid #ddd", borderRadius:"4px", fontSize:"14px", boxSizing:"border-box" },',
    '  table: { width:"100%", borderCollapse:"collapse", background:"white", borderRadius:"8px", overflow:"hidden", boxShadow:"0 2px 8px rgba(0,0,0,0.1)" },',
    '  th: { padding:"12px 16px", background:"#1e3a5f", color:"white", textAlign:"left", fontSize:"14px" },',
    '  td: { padding:"12px 16px", borderBottom:"1px solid #eee", fontSize:"14px" },',
    '  btnPrimary: { background:"#1e3a5f", color:"white", border:"none", padding:"10px 20px", borderRadius:"4px", cursor:"pointer", fontSize:"14px" },',
    '  btnSecondary: { background:"#95a5a6", color:"white", border:"none", padding:"10px 20px", borderRadius:"4px", cursor:"pointer", fontSize:"14px" }',
    '}',
])

# src/pages/Users.jsx
w("src/pages/Users.jsx", [
    'import { useState, useEffect } from "react"',
    'import api from "../api/axios"',
    '',
    'export default function Users() {',
    '  const [users, setUsers] = useState([])',
    '  const [showForm, setShowForm] = useState(false)',
    '  const [form, setForm] = useState({ name:"", email:"", password:"", role:"user" })',
    '  const [error, setError] = useState("")',
    '',
    '  useEffect(() => {',
    '    api.get("/api/users").then(r => setUsers(r.data))',
    '  }, [])',
    '',
    '  const handleCreate = async (e) => {',
    '    e.preventDefault()',
    '    setError("")',
    '    try {',
    '      const res = await api.post("/api/users", form)',
    '      setUsers([...users, res.data])',
    '      setShowForm(false)',
    '      setForm({ name:"", email:"", password:"", role:"user" })',
    '    } catch (err) {',
    '      setError(err.response?.data?.detail || "Error al crear usuario")',
    '    }',
    '  }',
    '',
    '  return (',
    '    <div style={styles.container}>',
    '      <div style={styles.header}>',
    '        <h2>Gestión de Usuarios</h2>',
    '        <button style={styles.btnPrimary} onClick={() => setShowForm(!showForm)}>+ Nuevo Usuario</button>',
    '      </div>',
    '',
    '      {showForm && (',
    '        <div style={styles.formCard}>',
    '          <h3>Crear Usuario</h3>',
    '          {error && <div style={styles.error}>{error}</div>}',
    '          <form onSubmit={handleCreate}>',
    '            <input style={styles.input} placeholder="Nombre *" value={form.name} onChange={e => setForm({...form, name:e.target.value})} required />',
    '            <input style={styles.input} type="email" placeholder="Email *" value={form.email} onChange={e => setForm({...form, email:e.target.value})} required />',
    '            <input style={styles.input} type="password" placeholder="Contraseña *" value={form.password} onChange={e => setForm({...form, password:e.target.value})} required />',
    '            <select style={styles.input} value={form.role} onChange={e => setForm({...form, role:e.target.value})}>',
    '              <option value="user">Usuario</option>',
    '              <option value="admin">Administrador</option>',
    '            </select>',
    '            <div style={{display:"flex", gap:"8px"}}>',
    '              <button style={styles.btnPrimary} type="submit">Crear</button>',
    '              <button style={styles.btnSecondary} type="button" onClick={() => setShowForm(false)}>Cancelar</button>',
    '            </div>',
    '          </form>',
    '        </div>',
    '      )}',
    '',
    '      <table style={styles.table}>',
    '        <thead><tr>',
    '          <th style={styles.th}>Nombre</th>',
    '          <th style={styles.th}>Email</th>',
    '          <th style={styles.th}>Rol</th>',
    '        </tr></thead>',
    '        <tbody>',
    '          {users.map(u => (',
    '            <tr key={u.id}>',
    '              <td style={styles.td}>{u.name}</td>',
    '              <td style={styles.td}>{u.email}</td>',
    '              <td style={styles.td}><span style={{...styles.badge, background: u.role === "admin" ? "#1e3a5f" : "#7f8c8d"}}>{u.role}</span></td>',
    '            </tr>',
    '          ))}',
    '        </tbody>',
    '      </table>',
    '    </div>',
    '  )',
    '}',
    '',
    'const styles = {',
    '  container: { padding:"24px" },',
    '  header: { display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:"20px" },',
    '  formCard: { background:"white", padding:"20px", borderRadius:"8px", boxShadow:"0 2px 8px rgba(0,0,0,0.1)", marginBottom:"20px" },',
    '  error: { background:"#fee", color:"#c00", padding:"10px", borderRadius:"4px", marginBottom:"12px", fontSize:"14px" },',
    '  input: { display:"block", width:"100%", padding:"10px", margin:"8px 0", border:"1px solid #ddd", borderRadius:"4px", fontSize:"14px", boxSizing:"border-box" },',
    '  table: { width:"100%", borderCollapse:"collapse", background:"white", borderRadius:"8px", overflow:"hidden", boxShadow:"0 2px 8px rgba(0,0,0,0.1)" },',
    '  th: { padding:"12px 16px", background:"#1e3a5f", color:"white", textAlign:"left", fontSize:"14px" },',
    '  td: { padding:"12px 16px", borderBottom:"1px solid #eee", fontSize:"14px" },',
    '  badge: { padding:"4px 10px", borderRadius:"12px", color:"white", fontSize:"12px", fontWeight:"bold" },',
    '  btnPrimary: { background:"#1e3a5f", color:"white", border:"none", padding:"10px 20px", borderRadius:"4px", cursor:"pointer", fontSize:"14px" },',
    '  btnSecondary: { background:"#95a5a6", color:"white", border:"none", padding:"10px 20px", borderRadius:"4px", cursor:"pointer", fontSize:"14px" }',
    '}',
])

# src/App.jsx
w("src/App.jsx", [
    'import { BrowserRouter, Routes, Route, Navigate } from "react-router-dom"',
    'import { AuthProvider } from "./context/AuthContext"',
    'import PrivateRoute from "./components/PrivateRoute"',
    'import Navbar from "./components/Navbar"',
    'import Login from "./pages/Login"',
    'import Tenders from "./pages/Tenders"',
    'import TenderDetail from "./pages/TenderDetail"',
    'import Clients from "./pages/Clients"',
    'import Products from "./pages/Products"',
    'import Users from "./pages/Users"',
    '',
    'function Layout({ children }) {',
    '  return (',
    '    <div style={{ minHeight:"100vh", background:"#f0f4f8" }}>',
    '      <Navbar />',
    '      <div>{children}</div>',
    '    </div>',
    '  )',
    '}',
    '',
    'export default function App() {',
    '  return (',
    '    <AuthProvider>',
    '      <BrowserRouter>',
    '        <Routes>',
    '          <Route path="/login" element={<Login />} />',
    '          <Route path="/" element={<PrivateRoute><Layout><Tenders /></Layout></PrivateRoute>} />',
    '          <Route path="/tenders/:id" element={<PrivateRoute><Layout><TenderDetail /></Layout></PrivateRoute>} />',
    '          <Route path="/clients" element={<PrivateRoute><Layout><Clients /></Layout></PrivateRoute>} />',
    '          <Route path="/products" element={<PrivateRoute><Layout><Products /></Layout></PrivateRoute>} />',
    '          <Route path="/users" element={<PrivateRoute adminOnly><Layout><Users /></Layout></PrivateRoute>} />',
    '          <Route path="*" element={<Navigate to="/" />} />',
    '        </Routes>',
    '      </BrowserRouter>',
    '    </AuthProvider>',
    '  )',
    '}',
])

# src/main.jsx
w("src/main.jsx", [
    'import { StrictMode } from "react"',
    'import { createRoot } from "react-dom/client"',
    'import App from "./App.jsx"',
    '',
    'createRoot(document.getElementById("root")).render(',
    '  <StrictMode>',
    '    <App />',
    '  </StrictMode>',
    ')',
])

# .env
w(".env", [
    'VITE_API_URL=http://127.0.0.1:8000',
])

print("\nTodos los archivos del frontend escritos correctamente!")
