import os

def w(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True) if os.path.dirname(path) else None
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"OK: {path}")

# app/models/tender.py
w("app/models/tender.py", [
    "from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Numeric, Enum, Text, UniqueConstraint",
    "from sqlalchemy.sql import func",
    "from sqlalchemy.orm import relationship",
    "import enum",
    "from app.core.database import Base",
    "",
    "class StatusEnum(str, enum.Enum):",
    '    activa = "activa"',
    '    por_cobrar = "por_cobrar"',
    '    perdida = "perdida"',
    '    finalizada = "finalizada"',
    "",
    "class Tender(Base):",
    '    __tablename__ = "tenders"',
    "",
    "    id = Column(Integer, primary_key=True, index=True)",
    "    title = Column(String, nullable=False)",
    "    description = Column(Text, nullable=True)",
    '    client_id = Column(Integer, ForeignKey("clients.id"), nullable=False)',
    "    status = Column(Enum(StatusEnum), nullable=False, default=StatusEnum.activa)",
    "    max_budget = Column(Numeric(12, 2), nullable=False)",
    "    total_amount = Column(Numeric(12, 2), nullable=False, default=0)",
    "    created_at = Column(DateTime(timezone=True), server_default=func.now())",
    "    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())",
    '    created_by = Column(Integer, ForeignKey("users.id"), nullable=True)',
    '    updated_by = Column(Integer, ForeignKey("users.id"), nullable=True)',
    "",
    '    client = relationship("Client", foreign_keys=[client_id])',
    '    products = relationship("TenderProduct", back_populates="tender")',
    "",
    "class TenderProduct(Base):",
    '    __tablename__ = "tender_products"',
    "",
    "    id = Column(Integer, primary_key=True, index=True)",
    '    tender_id = Column(Integer, ForeignKey("tenders.id"), nullable=False)',
    '    product_id = Column(Integer, ForeignKey("products.id"), nullable=False)',
    "    quantity = Column(Integer, nullable=False, default=1)",
    "    unit_price = Column(Numeric(10, 2), nullable=False)",
    "",
    '    tender = relationship("Tender", back_populates="products")',
    '    product = relationship("Product", foreign_keys=[product_id])',
    "",
    "    __table_args__ = (",
    '        UniqueConstraint("tender_id", "product_id", name="uq_tender_product"),',
    "    )",
])

# app/schemas/user.py
w("app/schemas/user.py", [
    "from pydantic import BaseModel, EmailStr",
    "from datetime import datetime",
    "from app.models.user import RoleEnum",
    "",
    "class UserCreate(BaseModel):",
    "    name: str",
    "    email: EmailStr",
    "    password: str",
    "    role: RoleEnum = RoleEnum.user",
    "",
    "class UserResponse(BaseModel):",
    "    id: int",
    "    name: str",
    "    email: str",
    "    role: RoleEnum",
    "    created_at: datetime",
    "",
    "    class Config:",
    "        from_attributes = True",
    "",
    "class LoginRequest(BaseModel):",
    "    email: EmailStr",
    "    password: str",
    "",
    "class TokenResponse(BaseModel):",
    "    access_token: str",
    '    token_type: str = "bearer"',
    "    user: UserResponse",
])

# app/schemas/client.py
w("app/schemas/client.py", [
    "from pydantic import BaseModel",
    "from typing import Optional",
    "from datetime import datetime",
    "",
    "class ClientCreate(BaseModel):",
    "    name: str",
    "    email: Optional[str] = None",
    "    phone: Optional[str] = None",
    "",
    "class ClientResponse(BaseModel):",
    "    id: int",
    "    name: str",
    "    email: Optional[str] = None",
    "    phone: Optional[str] = None",
    "    created_at: datetime",
    "",
    "    class Config:",
    "        from_attributes = True",
])

# app/schemas/product.py
w("app/schemas/product.py", [
    "from pydantic import BaseModel",
    "from decimal import Decimal",
    "from datetime import datetime",
    "",
    "class ProductCreate(BaseModel):",
    "    name: str",
    "    sku: str",
    "    unit_price: Decimal",
    "",
    "class ProductResponse(BaseModel):",
    "    id: int",
    "    name: str",
    "    sku: str",
    "    unit_price: Decimal",
    "    created_at: datetime",
    "",
    "    class Config:",
    "        from_attributes = True",
])

# app/schemas/tender.py
w("app/schemas/tender.py", [
    "from pydantic import BaseModel",
    "from typing import Optional, List",
    "from decimal import Decimal",
    "from datetime import datetime",
    "from app.models.tender import StatusEnum",
    "from app.schemas.client import ClientResponse",
    "from app.schemas.product import ProductResponse",
    "",
    "class TenderProductAdd(BaseModel):",
    "    product_id: int",
    "    quantity: int",
    "",
    "class TenderProductResponse(BaseModel):",
    "    id: int",
    "    product_id: int",
    "    quantity: int",
    "    unit_price: Decimal",
    "    product: ProductResponse",
    "",
    "    class Config:",
    "        from_attributes = True",
    "",
    "class TenderCreate(BaseModel):",
    "    title: str",
    "    description: Optional[str] = None",
    "    client_id: int",
    "    max_budget: Decimal",
    "",
    "class TenderStatusUpdate(BaseModel):",
    "    status: StatusEnum",
    "",
    "class TenderResponse(BaseModel):",
    "    id: int",
    "    title: str",
    "    description: Optional[str] = None",
    "    client_id: int",
    "    status: StatusEnum",
    "    max_budget: Decimal",
    "    total_amount: Decimal",
    "    created_at: datetime",
    "    client: Optional[ClientResponse] = None",
    "",
    "    class Config:",
    "        from_attributes = True",
    "",
    "class TenderDetailResponse(TenderResponse):",
    "    products: List[TenderProductResponse] = []",
    "",
    "    class Config:",
    "        from_attributes = True",
])

# app/services/user_service.py
w("app/services/user_service.py", [
    "from sqlalchemy.orm import Session",
    "from app.models.user import User",
    "from app.schemas.user import UserCreate",
    "from app.core.security import hash_password",
    "",
    "def get_all_users(db: Session):",
    "    return db.query(User).all()",
    "",
    "def get_user_by_email(db: Session, email: str):",
    "    return db.query(User).filter(User.email == email).first()",
    "",
    "def create_user(db: Session, user_data: UserCreate, created_by_id: int):",
    "    existing = get_user_by_email(db, user_data.email)",
    "    if existing:",
    '        raise ValueError("El email ya esta registrado")',
    "    new_user = User(",
    "        name=user_data.name,",
    "        email=user_data.email,",
    "        password_hash=hash_password(user_data.password),",
    "        role=user_data.role,",
    "        created_by=created_by_id,",
    "        updated_by=created_by_id",
    "    )",
    "    db.add(new_user)",
    "    db.commit()",
    "    db.refresh(new_user)",
    "    return new_user",
])

# app/services/client_service.py
w("app/services/client_service.py", [
    "from sqlalchemy.orm import Session",
    "from app.models.client import Client",
    "from app.schemas.client import ClientCreate",
    "",
    "def get_all_clients(db: Session, skip: int = 0, limit: int = 100):",
    "    return db.query(Client).offset(skip).limit(limit).all()",
    "",
    "def create_client(db: Session, client_data: ClientCreate, created_by_id: int):",
    "    new_client = Client(",
    "        name=client_data.name,",
    "        email=client_data.email,",
    "        phone=client_data.phone,",
    "        created_by=created_by_id,",
    "        updated_by=created_by_id",
    "    )",
    "    db.add(new_client)",
    "    db.commit()",
    "    db.refresh(new_client)",
    "    return new_client",
])

# app/services/product_service.py
w("app/services/product_service.py", [
    "from sqlalchemy.orm import Session",
    "from app.models.product import Product",
    "from app.schemas.product import ProductCreate",
    "",
    "def get_all_products(db: Session, skip: int = 0, limit: int = 100):",
    "    return db.query(Product).offset(skip).limit(limit).all()",
    "",
    "def create_product(db: Session, product_data: ProductCreate, created_by_id: int):",
    "    new_product = Product(",
    "        name=product_data.name,",
    "        sku=product_data.sku,",
    "        unit_price=product_data.unit_price,",
    "        created_by=created_by_id,",
    "        updated_by=created_by_id",
    "    )",
    "    db.add(new_product)",
    "    db.commit()",
    "    db.refresh(new_product)",
    "    return new_product",
])

# app/services/tender_service.py
w("app/services/tender_service.py", [
    "from sqlalchemy.orm import Session, joinedload",
    "from app.models.tender import Tender, TenderProduct, StatusEnum",
    "from app.models.product import Product",
    "from app.models.client import Client",
    "from app.schemas.tender import TenderCreate, TenderStatusUpdate, TenderProductAdd",
    "from decimal import Decimal",
    "",
    "VALID_TRANSITIONS = {",
    "    StatusEnum.activa: [StatusEnum.por_cobrar, StatusEnum.perdida],",
    "    StatusEnum.por_cobrar: [StatusEnum.finalizada],",
    "    StatusEnum.finalizada: [],",
    "    StatusEnum.perdida: [],",
    "}",
    "",
    "def get_all_tenders(db: Session, skip: int = 0, limit: int = 100):",
    "    return db.query(Tender).options(",
    "        joinedload(Tender.client)",
    "    ).offset(skip).limit(limit).all()",
    "",
    "def get_tender_by_id(db: Session, tender_id: int):",
    "    return db.query(Tender).options(",
    "        joinedload(Tender.client),",
    "        joinedload(Tender.products).joinedload(TenderProduct.product)",
    "    ).filter(Tender.id == tender_id).first()",
    "",
    "def create_tender(db: Session, tender_data: TenderCreate, created_by_id: int):",
    "    if tender_data.max_budget <= 0:",
    '        raise ValueError("El presupuesto maximo debe ser mayor a 0")',
    "    client = db.query(Client).filter(Client.id == tender_data.client_id).first()",
    "    if not client:",
    '        raise ValueError("El cliente especificado no existe")',
    "    new_tender = Tender(",
    "        title=tender_data.title,",
    "        description=tender_data.description,",
    "        client_id=tender_data.client_id,",
    "        max_budget=tender_data.max_budget,",
    '        total_amount=Decimal("0"),',
    "        status=StatusEnum.activa,",
    "        created_by=created_by_id,",
    "        updated_by=created_by_id",
    "    )",
    "    db.add(new_tender)",
    "    db.commit()",
    "    db.refresh(new_tender)",
    "    return new_tender",
    "",
    "def update_tender_status(db: Session, tender_id: int, status_data: TenderStatusUpdate, updated_by_id: int):",
    "    tender = db.query(Tender).filter(Tender.id == tender_id).first()",
    "    if not tender:",
    '        raise ValueError("Licitacion no encontrada")',
    "    allowed = VALID_TRANSITIONS.get(tender.status, [])",
    "    if status_data.status not in allowed:",
    "        raise ValueError(",
    "            f\"Transicion no permitida: no se puede cambiar de '{tender.status}' a '{status_data.status}'\"",
    "        )",
    "    tender.status = status_data.status",
    "    tender.updated_by = updated_by_id",
    "    db.commit()",
    "    db.refresh(tender)",
    "    return tender",
    "",
    "def add_product_to_tender(db: Session, tender_id: int, product_data: TenderProductAdd, updated_by_id: int):",
    "    tender = db.query(Tender).filter(Tender.id == tender_id).first()",
    "    if not tender:",
    '        raise ValueError("Licitacion no encontrada")',
    "    if tender.status != StatusEnum.activa:",
    '        raise ValueError("No se pueden agregar productos a una licitacion no activa")',
    "    product = db.query(Product).filter(Product.id == product_data.product_id).first()",
    "    if not product:",
    '        raise ValueError("El producto especificado no existe")',
    "    existing = db.query(TenderProduct).filter(",
    "        TenderProduct.tender_id == tender_id,",
    "        TenderProduct.product_id == product_data.product_id",
    "    ).first()",
    "    if existing:",
    '        raise ValueError("Este producto ya fue agregado a la licitacion")',
    "    subtotal = Decimal(str(product.unit_price)) * product_data.quantity",
    "    new_total = Decimal(str(tender.total_amount)) + subtotal",
    "    if new_total > Decimal(str(tender.max_budget)):",
    "        available = Decimal(str(tender.max_budget)) - Decimal(str(tender.total_amount))",
    "        raise ValueError(",
    "            f\"El total excede el presupuesto maximo de ${tender.max_budget}. Disponible: ${available}\"",
    "        )",
    "    tender_product = TenderProduct(",
    "        tender_id=tender_id,",
    "        product_id=product_data.product_id,",
    "        quantity=product_data.quantity,",
    "        unit_price=product.unit_price",
    "    )",
    "    db.add(tender_product)",
    "    tender.total_amount = new_total",
    "    tender.updated_by = updated_by_id",
    "    db.commit()",
    "    db.refresh(tender)",
    "    return get_tender_by_id(db, tender_id)",
])

# app/api/dependencies.py
w("app/api/dependencies.py", [
    "from fastapi import Depends, HTTPException, status",
    "from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials",
    "from sqlalchemy.orm import Session",
    "from app.core.database import get_db",
    "from app.core.security import decode_access_token",
    "from app.models.user import User, RoleEnum",
    "",
    "security = HTTPBearer()",
    "",
    "def get_current_user(",
    "    credentials: HTTPAuthorizationCredentials = Depends(security),",
    "    db: Session = Depends(get_db)",
    "):",
    "    token = credentials.credentials",
    "    payload = decode_access_token(token)",
    "    if not payload:",
    "        raise HTTPException(",
    "            status_code=status.HTTP_401_UNAUTHORIZED,",
    '            detail="Token invalido o expirado"',
    "        )",
    '    user = db.query(User).filter(User.id == payload.get("sub")).first()',
    "    if not user:",
    "        raise HTTPException(",
    "            status_code=status.HTTP_401_UNAUTHORIZED,",
    '            detail="Usuario no encontrado"',
    "        )",
    "    return user",
    "",
    "def require_admin(current_user: User = Depends(get_current_user)):",
    "    if current_user.role != RoleEnum.admin:",
    "        raise HTTPException(",
    "            status_code=status.HTTP_403_FORBIDDEN,",
    '            detail="No tienes permisos para realizar esta accion"',
    "        )",
    "    return current_user",
])

# app/api/routes/auth.py
w("app/api/routes/auth.py", [
    "from fastapi import APIRouter, Depends, HTTPException, status",
    "from sqlalchemy.orm import Session",
    "from app.core.database import get_db",
    "from app.core.security import verify_password, create_access_token",
    "from app.schemas.user import LoginRequest, TokenResponse, UserResponse",
    "from app.services.user_service import get_user_by_email",
    "",
    "router = APIRouter()",
    "",
    '@router.post("/login", response_model=TokenResponse)',
    "def login(login_data: LoginRequest, db: Session = Depends(get_db)):",
    "    user = get_user_by_email(db, login_data.email)",
    "    if not user or not verify_password(login_data.password, user.password_hash):",
    "        raise HTTPException(",
    "            status_code=status.HTTP_401_UNAUTHORIZED,",
    '            detail="Credenciales incorrectas"',
    "        )",
    '    token = create_access_token({"sub": str(user.id)})',
    "    return TokenResponse(",
    "        access_token=token,",
    '        token_type="bearer",',
    "        user=UserResponse.model_validate(user)",
    "    )",
])

# app/api/routes/users.py
w("app/api/routes/users.py", [
    "from fastapi import APIRouter, Depends, HTTPException, status",
    "from sqlalchemy.orm import Session",
    "from typing import List",
    "from app.core.database import get_db",
    "from app.api.dependencies import require_admin",
    "from app.schemas.user import UserCreate, UserResponse",
    "from app.services.user_service import create_user, get_all_users",
    "from app.models.user import User",
    "",
    "router = APIRouter()",
    "",
    '@router.get("/", response_model=List[UserResponse])',
    "def list_users(",
    "    db: Session = Depends(get_db),",
    "    current_user: User = Depends(require_admin)",
    "):",
    "    return get_all_users(db)",
    "",
    '@router.post("/", response_model=UserResponse, status_code=status.HTTP_201_CREATED)',
    "def register_user(",
    "    user_data: UserCreate,",
    "    db: Session = Depends(get_db),",
    "    current_user: User = Depends(require_admin)",
    "):",
    "    try:",
    "        return create_user(db, user_data, current_user.id)",
    "    except ValueError as e:",
    "        raise HTTPException(",
    "            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,",
    "            detail=str(e)",
    "        )",
])

# app/api/routes/clients.py
w("app/api/routes/clients.py", [
    "from fastapi import APIRouter, Depends, HTTPException, status",
    "from sqlalchemy.orm import Session",
    "from typing import List",
    "from app.core.database import get_db",
    "from app.api.dependencies import get_current_user, require_admin",
    "from app.schemas.client import ClientCreate, ClientResponse",
    "from app.services.client_service import create_client, get_all_clients",
    "from app.models.user import User",
    "",
    "router = APIRouter()",
    "",
    '@router.get("/", response_model=List[ClientResponse])',
    "def list_clients(",
    "    skip: int = 0,",
    "    limit: int = 100,",
    "    db: Session = Depends(get_db),",
    "    current_user: User = Depends(get_current_user)",
    "):",
    "    return get_all_clients(db, skip, limit)",
    "",
    '@router.post("/", response_model=ClientResponse, status_code=status.HTTP_201_CREATED)',
    "def create_new_client(",
    "    client_data: ClientCreate,",
    "    db: Session = Depends(get_db),",
    "    current_user: User = Depends(require_admin)",
    "):",
    "    return create_client(db, client_data, current_user.id)",
])

# app/api/routes/products.py
w("app/api/routes/products.py", [
    "from fastapi import APIRouter, Depends, HTTPException, status",
    "from sqlalchemy.orm import Session",
    "from typing import List",
    "from app.core.database import get_db",
    "from app.api.dependencies import get_current_user, require_admin",
    "from app.schemas.product import ProductCreate, ProductResponse",
    "from app.services.product_service import create_product, get_all_products",
    "from app.models.user import User",
    "",
    "router = APIRouter()",
    "",
    '@router.get("/", response_model=List[ProductResponse])',
    "def list_products(",
    "    skip: int = 0,",
    "    limit: int = 100,",
    "    db: Session = Depends(get_db),",
    "    current_user: User = Depends(get_current_user)",
    "):",
    "    return get_all_products(db, skip, limit)",
    "",
    '@router.post("/", response_model=ProductResponse, status_code=status.HTTP_201_CREATED)',
    "def create_new_product(",
    "    product_data: ProductCreate,",
    "    db: Session = Depends(get_db),",
    "    current_user: User = Depends(require_admin)",
    "):",
    "    try:",
    "        return create_product(db, product_data, current_user.id)",
    "    except Exception as e:",
    "        raise HTTPException(",
    "            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,",
    "            detail=str(e)",
    "        )",
])

# app/api/routes/tenders.py
w("app/api/routes/tenders.py", [
    "from fastapi import APIRouter, Depends, HTTPException, status",
    "from sqlalchemy.orm import Session",
    "from typing import List",
    "from app.core.database import get_db",
    "from app.api.dependencies import get_current_user",
    "from app.schemas.tender import TenderCreate, TenderResponse, TenderDetailResponse, TenderStatusUpdate, TenderProductAdd",
    "from app.services.tender_service import (",
    "    get_all_tenders,",
    "    get_tender_by_id,",
    "    create_tender,",
    "    update_tender_status,",
    "    add_product_to_tender",
    ")",
    "from app.models.user import User",
    "",
    "router = APIRouter()",
    "",
    '@router.get("/", response_model=List[TenderResponse])',
    "def list_tenders(",
    "    skip: int = 0,",
    "    limit: int = 100,",
    "    db: Session = Depends(get_db),",
    "    current_user: User = Depends(get_current_user)",
    "):",
    "    return get_all_tenders(db, skip, limit)",
    "",
    '@router.post("/", response_model=TenderResponse, status_code=status.HTTP_201_CREATED)',
    "def create_new_tender(",
    "    tender_data: TenderCreate,",
    "    db: Session = Depends(get_db),",
    "    current_user: User = Depends(get_current_user)",
    "):",
    "    try:",
    "        return create_tender(db, tender_data, current_user.id)",
    "    except ValueError as e:",
    "        raise HTTPException(",
    "            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,",
    "            detail=str(e)",
    "        )",
    "",
    '@router.get("/{tender_id}", response_model=TenderDetailResponse)',
    "def get_tender(",
    "    tender_id: int,",
    "    db: Session = Depends(get_db),",
    "    current_user: User = Depends(get_current_user)",
    "):",
    "    tender = get_tender_by_id(db, tender_id)",
    "    if not tender:",
    "        raise HTTPException(",
    "            status_code=status.HTTP_404_NOT_FOUND,",
    '            detail="Licitacion no encontrada"',
    "        )",
    "    return tender",
    "",
    '@router.patch("/{tender_id}/status", response_model=TenderResponse)',
    "def change_tender_status(",
    "    tender_id: int,",
    "    status_data: TenderStatusUpdate,",
    "    db: Session = Depends(get_db),",
    "    current_user: User = Depends(get_current_user)",
    "):",
    "    try:",
    "        return update_tender_status(db, tender_id, status_data, current_user.id)",
    "    except ValueError as e:",
    "        raise HTTPException(",
    "            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,",
    "            detail=str(e)",
    "        )",
    "",
    '@router.post("/{tender_id}/products", response_model=TenderDetailResponse, status_code=status.HTTP_201_CREATED)',
    "def add_product(",
    "    tender_id: int,",
    "    product_data: TenderProductAdd,",
    "    db: Session = Depends(get_db),",
    "    current_user: User = Depends(get_current_user)",
    "):",
    "    try:",
    "        return add_product_to_tender(db, tender_id, product_data, current_user.id)",
    "    except ValueError as e:",
    "        raise HTTPException(",
    "            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,",
    "            detail=str(e)",
    "        )",
])

# main.py
w("main.py", [
    "from fastapi import FastAPI",
    "from fastapi.middleware.cors import CORSMiddleware",
    "from app.api.routes import auth, users, clients, products, tenders",
    "",
    "app = FastAPI(",
    '    title="Sistema de Gestion de Licitaciones",',
    '    description="API para gestion de licitaciones comerciales - CSC",',
    '    version="1.0.0"',
    ")",
    "",
    "app.add_middleware(",
    "    CORSMiddleware,",
    '    allow_origins=["*"],',
    "    allow_credentials=True,",
    '    allow_methods=["*"],',
    '    allow_headers=["*"],',
    ")",
    "",
    'app.include_router(auth.router, prefix="/api/auth", tags=["Autenticacion"])',
    'app.include_router(users.router, prefix="/api/users", tags=["Usuarios"])',
    'app.include_router(clients.router, prefix="/api/clients", tags=["Clientes"])',
    'app.include_router(products.router, prefix="/api/products", tags=["Productos"])',
    'app.include_router(tenders.router, prefix="/api/tenders", tags=["Licitaciones"])',
    "",
    '@app.get("/")',
    "def root():",
    '    return {"message": "Sistema de Gestion de Licitaciones - CSC API"}',
])

# seed.py
w("seed.py", [
    "from app.core.database import SessionLocal",
    "from app.models.user import User, RoleEnum",
    "from app.core.security import hash_password",
    "",
    "def seed():",
    "    db = SessionLocal()",
    "    try:",
    '        existing = db.query(User).filter(User.email == "admin@csc.com").first()',
    "        if existing:",
    '            print("El usuario admin ya existe")',
    "            return",
    "        admin = User(",
    '            name="Administrador",',
    '            email="admin@csc.com",',
    '            password_hash=hash_password("admin123"),',
    "            role=RoleEnum.admin",
    "        )",
    "        db.add(admin)",
    "        db.commit()",
    '        print("Usuario admin creado exitosamente")',
    '        print("   Email: admin@csc.com")',
    '        print("   Password: admin123")',
    "    finally:",
    "        db.close()",
    "",
    'if __name__ == "__main__":',
    "    seed()",
])

print("\nTodos los archivos escritos correctamente!")
